# Generated by Django 6.1 on 2026-09-13 17:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField()),
                ('status_code', models.PositiveIntegerField(null=True)),
                ('latency_ms', models.PositiveIntegerField(null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitors.checkjob')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('interval_seconds', models.PositiveIntegerField(choices=[(30, '30 seconds'), (60, '60 seconds'), (300, '300 seconds'), (900, '900 seconds')], default=60)),
                ('timeout_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('enabled', models.BooleanField(default=True)),
                ('is_canary', models.BooleanField(default=False)),
                ('next_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('opening_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitors.checkresult')),
                ('recovery_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitors.checkresult')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitors.monitor')),
            ],
        ),
        migrations.AddField(
            model_name='checkresult',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitors.monitor'),
        ),
        migrations.AddField(
            model_name='checkjob',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitor'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=100)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.incident')),
            ],
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('monitor',), name='one_open_incident'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['monitor', '-checked_at'], name='monitors_ch_monitor_24c7e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkjob',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('monitor',), name='one_pending_check'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('incident', 'kind'), name='one_notification_per_transition'),
        ),
    ]
